### ISSUE TITLE
add an ace mode for `.sc` files

### ISSUE THREAD

**Issue by pq** [monome/maiden#106]
currently non-lua files default to a generic text editor but a custom mode for supercollider would be great.  as of yet, noone has written one so this would be on us.

things the mode could provide include:

* syntax highlighting
* basic parsing and error reporting
* indent smarts
* snippets and code completions

**Comment by mhetrick** [comment]
I opened an additional norns-wide issue for better SC tooling, so it might be good to cross-reference it here: https://github.com/monome/norns/issues/462

In addition to providing a method for editing ".sc" files in maiden, it would be useful to have the ability to restart the audio engine from maiden without restarting the entire device from the hardware.

**Comment by ngwese** [comment]
sc files are now exposed for simple editing. full editing support is likely best accomplished in the sc ide
