### ISSUE TITLE
filter .DS_Store or others from maiden menus

### ISSUE THREAD

**Issue by okyeron** [monome/maiden#110]
I started using Transmit today (from my Mac) to sftp to norns and now I'm seeing the invisible files ".DS_Store" and "._.DS_Store" in my maiden menu listings. (also using SAMBA, so I'm not sure which one is generating those DS_Store files)

I suppose these invisible files just need to be filtered out of the list?

![screen shot 2018-06-14 at 3 11 50 pm](https://user-images.githubusercontent.com/1909661/41435684-47de0892-6fe5-11e8-849c-88211978d57a.png)

**Comment by phonk** [comment]
seconded. Not really an important functionality but it ruins a bit Maiden's elegance.

**Comment by ngwese** [comment]
this shouldn’t be too bad to add. will look into it

**Comment by okyeron** [comment]
Wanted to ping this topic again - 
Noticed today that the .git directory shows up in subdirectories

Also - what to do about readme.md files? Probably leave them visible?

**Comment by simonvanderveldt** [comment]
Is there no way to exclude what you're sending to norns in the tool you're using?

**Comment by tehn** [comment]
we just need to filter normal dot files

I believe @ngwese is on it

**Comment by simonvanderveldt** [comment]
No chance someone wants to store something in a .dot dir and wants to edit that?

**Comment by ngwese** [comment]
This ticket should be addressed by this change once it is merged.
https://github.com/monome/maiden/commit/747e828f74727ab3a187217be59519c4452fd988

**Comment by ngwese** [comment]
Fixed as of https://github.com/monome/maiden/commit/747e828f74727ab3a187217be59519c4452fd988
