### ISSUE TITLE
allow for auto-updating of dust within maiden ui

### ISSUE THREAD

**Issue by jlmitch5** [monome/maiden#115]
I think it would be beneficial to update the state of dust through maiden.  An example flow:

* User connects their norns to wifi
* User accesses norns.local on their computer
* (maiden makes a GET request to the API to find out if there are new commits to dust)
* if there are new commits, something in the UI indicates “there are new updates to dust, click here to update”
* user clicks causing POST request to be made to the API, which pulls in the latest changes, giving the user access to use these scripts in norns.

Note that there will need to be some api analog to `git reset` as "naive" `git pull`ing will fail if changes to scripts tracked in the dust repo are changed.

---

I'm hoping to be able to explore this enhancement soon (acknowledging that it is a fairly big complicated feature that will definitely need some iteration before being able to be considered for merging).  Any feedback to the flow or how to approach this from the user's perspective is definitely appreciated, I am not hard set on the UX there.

**Comment by ngwese** [comment]
Closing this out given the restructuring of dust w/ the 2.0 firmware release. There is active work on providing some level of script/project management here: https://github.com/monome/maiden/projects/3
