### ISSUE TITLE
new layout: support multiple tabs and movable panes

### ISSUE THREAD

**Issue by ngwese** [monome/maiden#138]
allow more flexible ui layouts:
- multiple editor tabs, side by side, top/bottom arrangments
- movable file tabs, repl tabs

**Comment by tehn** [comment]
this is a naive question, but is it possible to do what we want without react?

**Comment by ngwese** [comment]
react is the framework which provides the structure for the app - specifically the ui/dom generation and state propagation. removing react essentially amounts to rewriting most of maiden.

there may be other options and i haven't given up on golden layout yet.

at the end of the day multiple editor tabs seems like the most critical feature from a layout perspective.

**Comment by ngwese** [comment]
some experimentation with https://www.npmjs.com/package/flexlayout-react in a test project proved promising and looks to be a much more react friendly path forward.

![image](https://user-images.githubusercontent.com/106652/55689919-92aaf580-593f-11e9-8f40-6f7881b610b4.png)

**Comment by simonvanderveldt** [comment]
Really liking the (dark themed) look of this!

**Comment by ngwese** [comment]
unlikely going to more forward with this in the current implementation
