### ISSUE TITLE
Build script writes executable as "maiden" not "maiden.arm"

### ISSUE THREAD

**Issue by okyeron** [monome/maiden#144]
Build script write executable as "maiden" not "maiden.arm"

**Comment by ngwese** [comment]
If I'm understanding this correct the suggestion is to have the release builds call the executable `maiden`?

That is probably fine however the change would need to be synchronized with modifications to the service units defined here: https://github.com/monome/norns-image/blob/master/config/norns-maiden.service#L10

**Comment by ngwese** [comment]
Is this sufficient? https://github.com/monome/maiden/commit/126a9b5691710f13dc0e037921e8a14d8aaa4885

**Comment by okyeron** [comment]
I'm not actually sure what the right solution is here. The service units you linked  point to maiden.arm and that's what has been included in the full release builds.

But... if you build maiden from source, you end up with a "maiden" executable instead of "maiden.arm"

I figured the easiest solution would be to change the build script to write the filename as "maiden.arm" instead of changing everything else.

**Comment by ngwese** [comment]
The challenge is that there really isn’t a build script, the setup just uses `go build` which always produces an executable called `maiden`. The normal mode of development as far as norns is concerned is to always cross compile for release builds because the full toolchain and dependencies consume 600-800MB of space just to produce the final 20MB artifact.

The recent addition of the release build script offers a way to eliminate the extension without affecting the cross compilation workflow. Coordinating with changes to installed unit files is more tricky.

**Comment by simonvanderveldt** [comment]
We can just remove the postfix from the unit, right?

**Comment by okyeron** [comment]
Oooh... Apologies. This looks way more complicated than I imagined.

Band-aid fix - update the documentation adding a step at the end to manually rename to "maiden.arm" when compiling from source on device?

**Comment by simonvanderveldt** [comment]
Is there a reason we would/should postfix the binary with `.arm`?

**Comment by ngwese** [comment]
There is no strong reason for the extension on the binary. It is a byproduct of how the development and cross compilation process was originally setup.

@simonvanderveldt - yes we can remove the postfix from the unit. Arguably this is a change which could happen as part of the norns 2.0 release. What isn't clear to me is if the 2.0 release will be through a new image or an update script as past releases have been done and how to best coordinate.

**Comment by simonvanderveldt** [comment]
@ngwese Nothing will change for 2.0 regarding the update, it'll be the same as before, so we can just make a PR to `dev` to change this to invoke `maiden` instead of `maiden.arm`

**Comment by ngwese** [comment]
fixed as of https://github.com/monome/maiden/pull/148
