### ISSUE TITLE
run script - file not found

### ISSUE THREAD

**Issue by okyeron** [monome/maiden#145]
Testing with the most recent updates (and norns 2.0 alpha) and `run script` is not finding scripts

relative path problem?

```
norns.script.load("study/study3.lua")
# script load: study/study3.lua
file not found: study/study3.lua
<ok>
```

**Comment by tehn** [comment]
testing this now.

**Comment by tehn** [comment]
working perfectly here. using maiden 0.11 on newest `dev` of norns.

i cloned https://github.com/monome/we into `~/dust/` and all is well

also works with `norns.script.load(...)`

can you provide any further details?

**Comment by okyeron** [comment]
Ah - i installed from master source rather than the release.

Let me go start again from the release version. Same problem here.

OK - looks like I had not updated with the norns #723 fix. Working now.

FWIW - http://norns.local/maiden/ does not load for me, but using IP address is OK. not sure if this is related or just something wacko on my install - although it was working before I changed maiden.

**Comment by tehn** [comment]
norns.local and zeroconf in general is often unreliable unfortunately. it's not related to the updates, or your install in particular. i often use the IP as well, which is why it got added to the screen display.

**Comment by okyeron** [comment]
Ah - FWIW on the `norns.local` thing - it's not the machine having a problem here. It's something with Maiden.

I can still access the device via SFTP to `norns.local`. 

`http://norns.local/doc/ `also works OK.
but...
`http://norns.local/maiden/` gives me a white page.

checking page source - looks like the paths to the JS files are a problem here? - or won't work from "/" with norns.local ?
```
<title>maiden</title><link href="/maiden/static/css/main.3c970d2b.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script type="text/javascript" src="/maiden/static/js/main.c88aaf4e.js"></script></body>
```

**Comment by tehn** [comment]
i can't reproduce this.

http://norns.local/maiden/ works

http://norns.local forwards to http://norns.local/maiden/

**Comment by okyeron** [comment]
FWIW - I did a "Clear browsing data" in Chrome and it fixed whatever was wrong. Bad cookie on that domain maybe?. Could be due to my compiling/running different versions of maiden today?
