### ISSUE TITLE
add lua api doc link

### ISSUE THREAD

**Issue by ngwese** [monome/maiden#152]
we need an easy way to pull up the docs from maiden

**Comment by ngwese** [comment]
additional thoughts to ponder. make json conf which provides links to the wiki in addition to local docs. recognize http links in scripts being edited.

**Comment by ngwese** [comment]
it's not pretty, the links are hardcoded, and the whole thing needs a refactor but i have made some progress on a quick and dirty popup with links to the main documentation (to be published on monome.org) and the api docs (served locally off the device).


hover over the `?` and a little menu link thing appears, clicking either link will open a new tab

![image](https://user-images.githubusercontent.com/106652/55455035-e5c72600-5596-11e9-9fc8-7109fab6213e.png)

**Comment by tehn** [comment]
this is fantastic, thank you!

**Comment by pq** [comment]
awesome!

maybe consider a little bit of UI to indicate that this is a link that will open a new tab?

a little out of step with the maiden aesthetic but the browser icon convention gets used a bunch to indicate something similar-ish.

![image](https://user-images.githubusercontent.com/67586/55479724-8dfae000-55d3-11e9-88a5-a826da30e129.png)

alternatively, maybe the "..." convention (often used to indicate a dialog will open but maybe close enough?)

![image](https://user-images.githubusercontent.com/67586/55479716-889d9580-55d3-11e9-82d1-96024736d2bb.png)

or maybe a "page" icon of some kind?

![image](https://user-images.githubusercontent.com/67586/55480067-488ae280-55d4-11e9-86b8-80772f67457c.png)

(sorry, all cribbed from IntelliJ where I'm stuck ATM.)

needless to say, cool beans!

**Comment by ngwese** [comment]
i went with the easy option for now; specifically "..."

the current implementation which i'm going to merge in looks like this when the pointer (not shown) hovers over the `?`:

![image](https://user-images.githubusercontent.com/106652/55529601-06ef4b80-5657-11e9-8785-25710cddc5c3.png)

basically:
- nixed the underlining but added darkening on link hover similar to existing buttons
- added the `...`
- added a subtle border on three sides to separate it out from the background a bit more

again this leaves a lot to be desired from an interaction and aesthetic standpoint but it gets the job done for now.

**Comment by ngwese** [comment]
calling this good enough for now. improvements can be handled as part of a new issue.

**Comment by pq** [comment]
Looks great! 👍
