### ISSUE TITLE
super low contrast for help menu text in chrome

### ISSUE THREAD

**Issue by ngwese** [monome/maiden#174]
There seems to be an accidental CSS regression or a change in behavior in recent versions of Chrome. The help menu renders in a much more faint gray in Chrome 78 (macOS) and Firefox 70 vs Firefox 69:

Firefox 69 / previous:
![image](https://user-images.githubusercontent.com/106652/67831776-9ef1ce00-fa9c-11e9-885c-0a6628174896.png)

Firefox 70 / Chrome 78
![image](https://user-images.githubusercontent.com/106652/67831797-b03ada80-fa9c-11e9-9c18-c1e175f56f72.png)

**Comment by ryanlaws** [comment]
#172 could probably help with this.

Using a contrast checker in tests may be helpful. Something like this maybe: https://github.com/monome/maiden/issues/174

**Comment by ngwese** [comment]
...something weird is going on. As of the most recent release the menu background is now appears semi-transparent.
