### ISSUE TITLE
maiden should update catalog on boot

### ISSUE THREAD

**Issue by ngwese** [monome/maiden#176]
several people have resorted to manual script/project downloads because maiden project catalogs are not updated automatically - additions made on github are not seen because a manual refresh is required. 

it seems advisable at a minimum to refresh the catalogs if/when network connectivity is established on boot. doing this would keep the catalogs reasonably up to date without manual intervention while avoiding periodic updates which could in the extreme cause glitches during recording or performance (however unlikely that would be)

**Comment by simonvanderveldt** [comment]
Is the option/button/action to refresh the catalog not clear enough maybe?
