### ISSUE TITLE
automatic catalog refresh

### ISSUE THREAD

**Issue by tehn** [monome/maiden#184]
moved from https://github.com/monome/norns/issues/1159

while it's documented that users need to refresh the community catalog to pull in new scripts, it often requires reiteration. eg: https://llllllll.co/t/grd/33768/63

curious if there's a way to automatically refresh the catalog once a network is detected, or once the user connects to maiden, so that any scripts which might have been released while the user was offline are presented without additional actions from the user?

**Comment by dndrks** [comment]
bump for visibility! @ngwese + @tehn , does this make sense to live on the maiden load side or just when norns connects to WIFI?

**Comment by ngwese** [comment]
i can look into refreshing the catalogs when the backend starts up (easy) or via some periodic event (not sure which event to hook into, possibly something to do asynchronous to in the background when the available page is accessed)

**Comment by ngwese** [comment]
i'm testing out a quick pass at something which will hopefully solve the problem or at least mitigate some of the confusion. essentially the logic is such that when the `maiden` server starts it:
- waits 15 seconds for the network to come up (assuming it is setup to auto connect)
- attempts to trigger update/downloading of _all_ catalogs on the device 5 time, waiting a minute in between each attempt
- if _any_ catalog changes on disk subsequent attempts are abandoned

https://github.com/monome/maiden/commit/247b93a4881317d60e56f8dec8076726b88ba2a5

the logic is crude at best. improvements could be made but would require more restructuring of the code than i'd like to get into right now. obviously this logic fails if:
- the network is not available when norns starts
- the catalogs have changed after norns has been running for over five minutes

if i can locate a go library that packages up monitoring of whether or not linux networking is up/down then i will consider changing the logic to check on changes to the networking status on the device...

**Comment by tehn** [comment]
i think your proposal is totally adequate for our purposes, which is to simply _reduce_ the issues.

perhaps we should alternatively consider changing the UI for refreshing catalogs... ie something like a button at the top which is "check for new scripts"

(i'm curious if we've ever had a script _removed_ from the community catalog??)

**Comment by ngwese** [comment]
i saw the additional posts / confusion. will look into some ui tweaks as well.
