### ISSUE TITLE
Maiden: you can undo a script back to the first loaded script.

### ISSUE THREAD

**Issue by jaggednz** [monome/maiden#208]
Steps to reproduce:
Go to a script (script a) in maiden
reload the browser
Navigate to a different script (script b)
Hit Ctrl + Z twice
Script a will now be shown as the contents of script b

Chrome latest on Mac OS

**Comment by ngwese** [comment]
this is likely the same as #186

**Comment by catfact** [comment]
seems like it, closing as dupe
