### ISSUE TITLE
autocorrect in norns REPL is counterproductive

### ISSUE THREAD

**Issue by xmacex** [monome/maiden#209]
Autocorrect and autocapitalization for Maiden input text area are counterproductive, since they'll do a poor job for programming languages.

In the below, I've typed `opz` and pressed the space. Autocorrect turned it to `plz`. YMMV

![Screenshot_20210603-031542](https://user-images.githubusercontent.com/879300/120571326-22626680-c41a-11eb-965a-73e527b5f0bc.jpg)

I figure adding `autocorrect=off` and `autocapitalize=none` to the `ReplOnput` component input text area would do it. Perhaps together with `autocomplete=off` too.

https://github.com/monome/maiden/blob/5bbb3693ff0cbc7f467e99ffd81dd65ee8bc3cd0/web/src/repl.js#L103

**Comment by xmacex** [comment]
Super. Just a little note that while `autocapitalize` takes values of `off` or `none` according to [Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize), Apple considers `off` deprecated and wants `none` instead.

¯\_(ツ)_/¯

I haven't checked a more authoritative source than Mozilla, and am an Android Chrome (Beta) use myself but i reckon there's Apple users among norns users. I don't know how Apple devices react to `off`.
 
Anyhow stay rad, stay safe, stay bleeping.

**Comment by ngwese** [comment]
I specifically tested on iOS and it seemed happy. No warnings and no capitals so I just ran with off
