### ISSUE TITLE
add editor button to force reload the current module

### ISSUE THREAD

**Issue by ngwese** [monome/maiden#22]
when developing a (lua) module changes don't get picked up if the module has been already been loaded via `require`.

it is possible to force a module to get reloaded by setting `package.loaded.<module_name> = nil` then calling `require '<module_name>'`

to facilitate module development it might be nice to have button in the editor which sends this to the repl (after a save), or by making the save button more smart...

**Comment by pq** [comment]
following up on a [conversation on lines](https://llllllll.co/t/norns-help/14016/192), as @catfact pointed out elsewhere a work-around is to explicitly un-load the module (to the extent that you can).

the basic idea can be expressed in a helper function, like this:

```lua
function reload(module_name)
  if (package.loaded[module_name] ~= nil) then
    package.loaded[module_name] = nil
    _G[module_name] = nil
  end
  return require(module_name)
end
```

that you use in your script like this:

```lua
-- reload, really.
local foo = sys_utils.reload("foo")
```

in the simplest cases this works well enough during development.

**Comment by ngwese** [comment]
this is largely no longer an issue now that `include(...)` is a thing
