### ISSUE TITLE
sc repl commands do not get evaluated

### ISSUE THREAD

**Issue by ngwese** [monome/maiden#25]
it would appear that `sclang` isn't evaluating commands when run under `ws-wrapper`.

command strings (including a trailing \n) are being written to the pipe opened for `sclang` (confirmed by hacking `ws-wrapper`). it is possible that `sclang` is expecting a (pseudo) terminal or something.

**Comment by simonvanderveldt** [comment]
> it is possible that sclang is expecting a (pseudo) terminal or something.

Seems like this is the main part of the code directly related to the `sclang` client https://github.com/supercollider/supercollider/blob/develop/lang/LangSource/SC_TerminalClient.cpp
My C(++) isn't good enough to judge if there's something in there that requires a terminal or not though.

**Comment by ngwese** [comment]
...thanks that does actually help. I'm wondering if the build of `sclang` we are using is built with readline enabled. I could see that causing problems. Lines like there are telling:
https://github.com/supercollider/supercollider/blob/develop/lang/LangSource/SC_TerminalClient.cpp#L627-L636

**Comment by catfact** [comment]
you're right, it totally uses readline. (seems clear from the interactions available on the REPL when you run sclang)

**Comment by catfact** [comment]
we could actually fall back on something silly like sending each line over OSC...

**Comment by ngwese** [comment]
i'd like to do some more digging. looking at the code i references above it gives me the impression that there is a flag or some other configuration which can be set which informs `sclang` that it is being driven by an ide not directly by a person therfore it turns off readline (even if compiled with it).

if this can be handled via configuration that seems best.

**Comment by ngwese** [comment]
i think i've found a solution. `sclang` has a `-i` flag which allows one to pass in an ide name which is ultimately exposed to `sclang` code as part of the platform abstraction so that the class library can tailor its behavior for a given ide client. as a side effect when an ide name is set that _disables_ all the readline logic so we can use `sclang -i maiden` to effectively turn off readline.

the second part of the puzzle is that the sclang input handling logic expects to find a specific "command" byte at then end of an incoming buffer which signals what to do:
https://github.com/supercollider/supercollider/blob/develop/lang/LangSource/SC_TerminalClient.cpp#L334-L361

if i hack `maiden` to send commands terminated with `0x1b` instead of `\n` then `sclang` evaluates the command...
