### ISSUE TITLE
basic keyboard accelerators

### ISSUE THREAD

**Issue by ngwese** [monome/maiden#26]
need basic keyboard accelerators (aka shortcuts)

ctrl/⌘ +

- [x] S - save
- [x] P - play
- [x] B - toggle sidebar
- [x] E - toggle repl
- [ ] ? - move focus between editor, repl, explorer
- [ ] ? - show matron repl
- [ ] ? - show sc repl

**Comment by ngwese** [comment]
@pq i’m thinking this issue is effectively resolved (we have the basics cover)

shall we close this out?

**Comment by pq** [comment]
sounds good!
