### ISSUE TITLE
restyle ui

### ISSUE THREAD

**Issue by ngwese** [monome/maiden#63]
restyle ui based on laborcamp mockup in order to better harmonize with the maiden icons.

![image](https://user-images.githubusercontent.com/106652/39952901-56fe71f4-5555-11e8-9b55-7f43b2779972.png)

/cc @jlmitch5

**Comment by synthetiv** [comment]
Is this something people are still talking about / working on? I'd love to help out. The mockup looks nice.

**Comment by ngwese** [comment]
There hasn’t been much work on this front beyond the original hack to see how feasible it was to mimic the mock-up. 

There are some minor changes which have already been merged that simplified some of the styling around the file tree (blending it with the side bar)

Ideas, suggestions, and PRs are always welcome. If an ambitious restyle is something people are interested in working on it would be good to start with some mockups so we can discuss.

**Comment by ngwese** [comment]
...initial restyling work has completely bit rotten and is unlikely to be pursued.
