### ISSUE TITLE
make configure icon toggle instead of just open

### ISSUE THREAD

**Issue by jlmitch5** [monome/maiden#87]
I feel like I've tried to click the configure icon after I am finishing editing the config options to close the pane (similar to the way the toggle file viewer icon works).

Also would probably want to update the tooltip to say "toggle configure pane" or something similar, and make sure the key command works for both on and off toggle.

Definitely open to discussion and other perspectives on this issue.

**Comment by ngwese** [comment]
Closing out resolved issue.
