### ISSUE TITLE
repl styling: make the matron and sc selectors more prominent

### ISSUE THREAD

**Issue by pq** [monome/maiden#90]
a nit, but currently the indication of what repl you're in is a bit under-stated.

![image](https://user-images.githubusercontent.com/67586/40547503-e6fa5822-5fe6-11e8-8d61-9351f4715b96.png)

compare, for example, with vscode for inspiration:

![image](https://user-images.githubusercontent.com/67586/40547727-8693f3de-5fe7-11e8-825f-a29c359440c0.png)

a little resizing, padding and perhaps color to add contrast could make it (lacking the word) more "balanced"?

related to #63

/cc @jlmitch5

**Comment by synthetiv** [comment]
Seeing the Good First Issue tag, I thought I'd go ahead and make a PR for this: #163
