### ISSUE TITLE
change maiden to run on port 80 (instead of 5000)

### ISSUE THREAD

**Issue by ngwese** [monome/maiden#92]
the solution should bind port 80 then lower permissions to run as `we`.

the systemd unit will need some adjustment and possibly the backend code to get the permissions lowering don correctly.

/cc @tehn

**Comment by nf** [comment]
@ngwese that's correct, Go doesn't use the libc bind function to listen, so any method that hijacks libc calls won't work.

Does norns use systemd for initialization? I think @artfwo's suggestion of listening in systemd and passing an fd to maiden should work.

You can create a net.Listener (that you can pass to http.Serve) from a fd number like so:

```
l, err = net.FileListener(os.NewFile(uintptr(fd), "http"))
``` 

[This doc](https://liquidat.wordpress.com/2018/01/04/howto-run-programs-as-non-root-user-on-privileged-ports-via-systemd/) looks relevant.

I am happy to help with this any way I can.

**Comment by ngwese** [comment]
@nf - from the looks of things you know your way around go alot more that i do so if you see a path where systemd hands off sockets to the backend i'm all for it.

norns is using systemd to manage processes...

**Comment by nf** [comment]
@ngwese sure, happy to investigate.

**Comment by nf** [comment]
I just sent PR #94. The corresponding systemd change would be something like this:

```
$ cat /etc/systemd/system/maiden.socket
[Unit]
Description=maiden socket

[Socket]
ListenStream=80
NoDelay=true
```

And then in `maiden.service` (wherever that is) add this to the `[Unit]` section:

```
Requires=maiden.socket
```

**Comment by nf** [comment]
Should this be closed now? 😊

**Comment by pq** [comment]
@nf : just loaded this change.  so nice.  cheers! 🍻
