### ISSUE TITLE
REPL entry styling

### ISSUE THREAD

**Issue by tehn** [monome/maiden#99]
sorry for the micro-suggestion

- the `>>` should be the same style as the text that gets entered.
- i'm somehow much more used to seeing a single `>` instead of a double.
- vertical center 

![screen shot 2018-06-03 at 5 33 39 pm](https://user-images.githubusercontent.com/246896/40891480-5e871e88-6754-11e8-9ab0-056c08580eff.png)

**Comment by ngwese** [comment]
the double >> was just a reflex as that is the python repl default (and i spend a lot of time in python over the years)

agreed on the centering difference being annoying - the source of that is rendering differences between a span and a textarea dom element.

**Comment by tehn** [comment]
aha! feel free to keep the `>>` then, i don't get out much :)
